# Generated by Django 2.1.7 on 2019-06-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_remove_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(to='ecom.Item'),
        ),
    ]
