# Generated by Django 2.1.7 on 2019-06-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_auto_20190616_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
    ]
