# Generated by Django 2.1.7 on 2019-08-23 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_remove_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
